# Generated by Django 5.1 on 2024-09-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'User')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
